apiVersion: v1
kind: Service
metadata:
  name: myapp-svc # 创建一个 name 为 myapp-svc 的服务
spec:
  ports:
    - port: 80 # 服务在 80 端口接收请求,并路由到标签选择器为 app=myapp-rs 的 Pod 的 8080 上
      targetPort: 8080
  selector:
    app: myapp-rs