apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-labels # Pod 启动时的主机名
  labels:
    app: myapp-labels
    env: test
    creation-method: manual
spec:
  containers:
    - name: myapp
      image: itguang/kubia
      ports:
        - containerPort: 8080
          protocol: TCP
          name: myapp-test1

