apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  rules:
    - host: example.myapp.com
      http:
        paths:
          - backend:
              serviceName: myapp-svc
              servicePort: 80

