apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-nodeport
spec:
  type: NodePort # 把 Service 设置为 NodePort 类型
  ports:
    - port: 80 # service 端口
      targetPort: 8080 # container 端口
      nodePort: 30001 # Node 节点端口: 必须范围: 30000-32767
  selector:
    app: myapp-rs # 标签选择器

