apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-loadbalance
spec:
  type: LoadBalancer # 创建一个 LoadBalance 类型的 Service
  ports:
    - port: 80 # loadBalance 暴露的端口
      targetPort: 8080
  selector:
    app: myapp-rs