kind: Pod
apiVersion: v1
metadata:
  name: myapp
  labels:
    app: myapp-labels
spec:
  containers:
    - name: myapp
      image: itguang/kubia
      ports:
        - containerPort: 8080
          protocol: TCP
          name: myapp-test1

