apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # 访问模式,只能被一个 Pod 写入
#    - ReadOnlyMany
#    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Delete  PVC 删除后的 PV 保留 策略
  # 配置阿里云/腾讯云 高效能磁盘,需要装 k8s 插件,看考各自官网
  nfs:
    path: /app
    server: 127.0.0.1
    readOnly: true

